<a href="https://colab.research.google.com/github/AthxrvA7/AI-Ml-Projects/blob/main/ChatBot_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from datasets import load_dataset
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
dataset = load_dataset("emotion")
df = pd.DataFrame(dataset['train'])
df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [ ]:
labels = ["sadness", "joy", "love", "anger", "fear", "surprise"]

df['emotions'] = df['label'].apply(lambda x: labels[x])
df.head()

                                                text  label emotions
0                            i didnt feel humiliated      0  sadness
1  i can go from feeling so hopeless to so damned...      0  sadness
2   im grabbing a minute to post i feel greedy wrong      3    anger
3  i am ever feeling nostalgic about the fireplac...      2     love
4                               i am feeling grouchy      3    anger

In [ ]:
vectorizer = TfidfVectorizer()

x = vectorizer.fit_transform(df['text'])
y = df['label']

print(x.shape)

(16000, 15186)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [ ]:
def predict_emotion(text):
    vec = vectorizer.transform([text])
    pred = model.predict(vec)[0]
    return labels[pred]

print(predict_emotion("I feel amazing"))

surprise

In [ ]:
emotion_history = []

def weighted_emotions(history):
    weights = {}
    n = len(history)

    for i, emotion in enumerate(history):
        weight = i + 1

        if emotion in weights:
            weights[emotion] += weight
        else:
            weights[emotion] = weight

    return weights

In [ ]:
def weighted_emotions(history):
    weights = {}
    n = len(history)

    for i, emotion in enumerate(history):
        weight = i + 1

        if emotion in weights:
            weights[emotion] += weight
        else:
            weights[emotion] = weight

    return weights

In [ ]:
def respond_to_emotion(emotion):
    if emotion == "joy":
        return "That's great to hear!"

    elif emotion == "sadness":
        return "I'm here for you."

    elif emotion == "anger":
        return "Take a deep breath."

    elif emotion == "fear":
        return "It's okay, you're safe."

    elif emotion == "surprise":
        return "That’s unexpected!"

    else:
        return "I understand."

In [ ]:
def emotional_agent(text):
    emotion = predict_emotion(text)

    emotion_history.append(emotion)

    if len(emotion_history) > 5:
        emotion_history.pop(0)

    weights = weighted_emotions(emotion_history)

    dominant = max(weights, key=weights.get)

    response = respond_to_emotion(dominant)

    return emotion, dominant, response

In [ ]:
while True:
    text = input("You: ")

    emotion, dominant, response = emotional_agent(text)

    print("Detected Emotion:", emotion)
    print("Mood:", dominant)
    print("Bot:", response)

You: Hey
Detected: sadness
Mood: sadness
Bot: I'm here for you.
You: I am feeling good
Detected: joy
Mood: joy
Bot: That's great to hear!
You: I dont know what to feel
Detected: joy
Mood: joy
Bot: That's great to hear!
You: Sad
Detected: sadness
Mood: sadness
Bot: I'm here for you.
You: I don’t know what to feel
Detected: sadness
Mood: sadness
Bot: I'm here for you.

KeyboardInterrupt: Interrupted by user